safe: true
lsi: false
pygments: true
source: _source
destination: _site

kvasirsec_repo:   https://github.com/KvasirSecurity
kvasir_repo:      https://github.com/KvasirSecurity/Kvasir

cdn_css:          //netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css
cdn_theme_css:    //netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css
cdn_js:           //netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js
